import { NextRequest, NextResponse } from "next/server";
import { getSupabase } from "@/lib/supabase";

export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get("id");

  if (!id) {
    return NextResponse.json({ error: "Missing id" }, { status: 400 });
  }

  const { data, error } = await getSupabase()
    .from("audits")
    .select("id, status, brand, category, website_url, result, overall_score, overall_verdict, unlocked, unlocked_at, created_at")
    .eq("id", id)
    .single();

  if (error || !data) {
    return NextResponse.json({ error: "Audit not found" }, { status: 404 });
  }

  // Fetch score history: last 5 completed audits for the same brand (excluding current)
  const { data: history } = await getSupabase()
    .from("audits")
    .select("id, overall_score, created_at")
    .eq("brand", data.brand)
    .eq("status", "complete")
    .neq("id", id)
    .order("created_at", { ascending: false })
    .limit(5);

  // Strip premium-only fields from the result JSON when the audit has not
  // been purchased. These fields are generated by generatePremiumContent()
  // and should not be freely readable by anyone who happens to have the UUID.
  const PREMIUM_FIELDS = [
    "opportunityCalculator",
    "positioningBrief",
    "onlinePresence",
    "contentGapMap",
    "roadmap",
  ] as const;

  let safeResult = data.result;
  if (!data.unlocked && safeResult && typeof safeResult === "object") {
    safeResult = { ...safeResult } as Record<string, unknown>;
    for (const field of PREMIUM_FIELDS) {
      delete (safeResult as Record<string, unknown>)[field];
    }
  }

  return NextResponse.json({ ...data, result: safeResult, scoreHistory: history ?? [] });
}
